INSERT INTO project_menu_section (hash, title, description, cta_title, cta_url, sort_order)
VALUES ('programming-languages',
        'Языки программирования',
        'Программируйте ПЛК и микроконтроллеры на инновационных языках быстрее и проще',
        'Перейти в центр Языков программирования',
        '/projects/programming-languages',
        10),
       ('ride-cloud',
        'Облачная среда разработки RIDE',
        'Работайте с web-IDE и облачными инструментами разработки и обучения.',
        'Перейти в RIDE',
        '/projects/ride',
        20),
       ('requirements-engineering-and-edtl',
        'Инженерия требований и EDTL',
        'Формализуйте и проверяйте требования к системам управления.',
        'Перейти к EDTL',
        '/projects/requirements-engineering-and-edtl',
        30),
       ('distributed-microcontrollers',
        'Распределенные микроконтроллерные системы',
        'Создавайте распределённые системы управления на базе процесс-ориентированного подхода.',
        'Перейти к распределённым системам',
        '/projects/distributed-microcontroller-systems',
        40),
       ('static-analysis-tools',
        'Инструменты статического анализа',
        'Используйте статический анализ для контроля качества и поведения process-oriented программ.',
        'Перейти к инструментам анализа',
        '/projects/static-analysis',
        50);

INSERT INTO project_menu_item (section_id, title, description, url, image_url, highlighted, sort_order)
SELECT s.id,
       v.title,
       v.description,
       v.url,
       v.image_url,
       v.highlighted,
       v.sort_order
FROM project_menu_section s
         JOIN (VALUES ('programming-languages', 'Reflex',
                       'Язык для разработки ПО микроконтроллеров во встраиваемых системах с использованием методики процесс-ориентированного программирования',
                       '/projects/reflex', NULL, TRUE, 10),
                      ('programming-languages', 'poST',
                       'Процесс-ориентированное расширение языка Structured Text (ST) для программирования алгоритмически сложных управляющих программ для ПЛК',
                       '/projects/post', NULL, FALSE, 20),
                      ('programming-languages', 'IndustrialC',
                       'Специализированный процесс-ориентированный язык программирования для задач промышленной автоматизации и систем реального времени с синтаксисом, похожим на Cи',
                       '/projects/industrial-c', NULL, FALSE, 30),
                      ('ride-cloud', 'RIDE',
                       'Theia-based web IDE для языка Reflex и смежных инструментов process-oriented разработки.',
                       '/projects/ride', NULL, TRUE, 10),
                      ('requirements-engineering-and-edtl', 'EDTL',
                       'Язык и инструменты для описания и автоматизированной обработки событийно-ориентированных временных требований.',
                       '/projects/requirements-engineering-and-edtl', NULL, TRUE, 10),
                      ('distributed-microcontrollers', 'Distributed Control',
                       'Подходы и инфраструктура для распределённых систем управления с сохранением семантики гиперпроцесса.',
                       '/projects/distributed-microcontroller-systems', NULL, TRUE, 10),
                      ('static-analysis-tools', 'Static Analysis',
                       'Инструменты исследования сложности, структуры и свойств process-oriented спецификаций.',
                       '/projects/static-analysis', NULL, TRUE, 10)) AS v(section_hash, title, description, url, image_url, highlighted, sort_order)
              ON s.hash = v.section_hash;

INSERT INTO project_menu_promo (section_id, title, description, url, image_url, sort_order)
SELECT s.id,
       v.title,
       v.description,
       v.url,
       v.image_url,
       v.sort_order
FROM project_menu_section s
         JOIN (VALUES ('programming-languages', 'Что нового?',
                       'Изучите новые возможности и передовые технологии',
                       '/projects/news',
                       '/files/projects-menu/whats-new.png',
                       10),
                      ('programming-languages', 'Истории успеха наших пользователей',
                       'Узнайте, как технологии Poprog ускоряют переход предприятий в Индустрию 4.0',
                       '/projects/success-stories',
                       '/files/projects-menu/success-stories.png',
                       20)) AS v(section_hash, title, description, url, image_url, sort_order)
              ON s.hash = v.section_hash;
